In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("social_media_engagement_dataset.csv")
df.head()

,platform,post_type,post_length,views,likes,comments,shares,engagement_rate
0,Facebook,Text,62,91660,2968,276,346,0.039166
1,Instagram,Video,104,113115,4164,632,406,0.045989
2,Facebook,Video,46,36043,3125,188,100,0.094692
3,Facebook,Image,39,124886,5970,948,578,0.060023
4,Instagram,Video,42,82831,8212,1104,334,0.116502

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   platform         10000 non-null  object
 1   post_type        10000 non-null  object
 2   post_length      10000 non-null  int64
 3   views            10000 non-null  int64
 4   likes            10000 non-null  int64
 5   comments         10000 non-null  int64
 6   shares           10000 non-null  int64
 7   engagement_rate  10000 non-null  float64
dtypes: float64(1), int64(5), object(2)
memory usage: 625.1+ KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

platform           0
post_type          0
post_length        0
views              0
likes              0
comments           0
shares             0
engagement_rate    0
dtype: int64

In [7]:
df["views"].value_counts()

views
102751    3
168373    3
199035    3
195808    2
183734    2
         ..
128762    1
8984      1
237359    1
210150    1
183199    1
Name: count, Length: 9795, dtype: int64

In [8]:
df["platform"].value_counts()

platform
Instagram    3354
Twitter      3347
Facebook     3299
Name: count, dtype: int64

### Observation:We have 3 Unique pltforms

In [9]:
df["post_type"].value_counts()

post_type
Image    3370
Video    3333
Text     3297
Name: count, dtype: int64

In [10]:
df.head()

,platform,post_type,post_length,views,likes,comments,shares,engagement_rate
0,Facebook,Text,62,91660,2968,276,346,0.039166
1,Instagram,Video,104,113115,4164,632,406,0.045989
2,Facebook,Video,46,36043,3125,188,100,0.094692
3,Facebook,Image,39,124886,5970,948,578,0.060023
4,Instagram,Video,42,82831,8212,1104,334,0.116502

**Observations:**

- **platform** and **post_type** are categorical data columns.

- Remaining all are **real numerical** data columns.

- There are **no missing vlaues**.

- There are **no duplicates** in this data.

**Problem Statement:**

- Create a Machine Learning Model to predict **Social Media Engagement Rate**.

    - Based on above problem statement, **engagement_rate** is target variable.

    - **engagement_rate** is a **real numerical** data column. Hence, It is a **regression** task.

### select target variable and input var

In [25]:
y=df["engagement_rate"]
X=df.drop(columns="engagement_rate")
print(y.shape)
print(X.shape)

(10000,)
(10000, 7)

### Split the data into training and testing

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [28]:
print(X_train.shape)
print(X_test.shape)

(8000, 7)
(2000, 7)

In [29]:
X_train_cat=X_train[["platform","post_type"]]
X_test_cat=X_test[["platform","post_type"]]

In [32]:
X_train_cat

       platform post_type
7416  Instagram     Image
9833  Instagram      Text
1636   Facebook     Video
4323   Facebook     Image
6299   Facebook     Image
...         ...       ...
4125    Twitter     Image
5601  Instagram      Text
7121  Instagram      Text
758    Facebook     Image
6159  Instagram     Image

[8000 rows x 2 columns]

### a.ONE HOT ENCODING

In [33]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [34]:
X_train_cat_tr=ohe.fit_transform(X_train_cat)
x_test_cat_tr=ohe.transform(X_test_cat)
print(type(x_test_cat_tr))

<class 'scipy.sparse._csr.csr_matrix'>

In [35]:
X_train_catdf=pd.DataFrame(X_train_cat_tr.toarray())
X_train_catdf

        0    1    2    3    4    5
0     0.0  1.0  0.0  1.0  0.0  0.0
1     0.0  1.0  0.0  0.0  1.0  0.0
2     1.0  0.0  0.0  0.0  0.0  1.0
3     1.0  0.0  0.0  1.0  0.0  0.0
4     1.0  0.0  0.0  1.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...
7995  0.0  0.0  1.0  1.0  0.0  0.0
7996  0.0  1.0  0.0  0.0  1.0  0.0
7997  0.0  1.0  0.0  0.0  1.0  0.0
7998  1.0  0.0  0.0  1.0  0.0  0.0
7999  0.0  1.0  0.0  1.0  0.0  0.0

[8000 rows x 6 columns]

In [20]:
X_train_catdf.head()

     0    1    2    3    4    5
0  0.0  0.0  1.0  1.0  0.0  0.0
1  0.0  0.0  1.0  0.0  0.0  1.0
2  0.0  0.0  1.0  1.0  0.0  0.0
3  0.0  1.0  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0  0.0  1.0

In [36]:
X_train.head()[["platform","post_type"]]

       platform post_type
7416  Instagram     Image
9833  Instagram      Text
1636   Facebook     Video
4323   Facebook     Image
6299   Facebook     Image

In [39]:
#label Encoder(ordinal encoder)
from sklearn.preprocessing import OrdinalEncoder
le=OrdinalEncoder()

In [41]:
X_train_cat_le=le.fit_transform(X_train_cat)
le=OrdinalEncoder()

In [43]:
X_train_cat_le=le.fit_transform(X_train_cat)
X_test_cat_le=le.transform(X_test_cat)

In [44]:
print(type(X_train_cat_le))

<class 'numpy.ndarray'>

In [46]:
X_train_ledf=pd.DataFrame(X_train_cat_le,columns=X_train_cat.columns)
X_train_ledf.head()

   platform  post_type
0       1.0        0.0
1       1.0        1.0
2       0.0        2.0
3       0.0        0.0
4       0.0        0.0

In [47]:
X_train_ledf["platform"].value_counts()

platform
2.0    2695
1.0    2664
0.0    2641
Name: count, dtype: int64

In [48]:
X_train_cat["platform"].value_counts()

platform
Twitter      2695
Instagram    2664
Facebook     2641
Name: count, dtype: int64

In [51]:
oe=OrdinalEncoder(categories=[["Twitter","Instagram","Facebook"],
                              ["Image","Video","Text"]])
a=oe.fit_transform(X_train_cat)
a1=oe.transform(X_test_cat)

In [52]:
a_df=pd.DataFrame(a,columns=X_train_cat.columns)
a_df.head()

   platform  post_type
0       1.0        0.0
1       1.0        2.0
2       2.0        1.0
3       2.0        0.0
4       2.0        0.0

In [55]:
a_df["platform"].value_counts()

platform
0.0    2695
1.0    2664
2.0    2641
Name: count, dtype: int64

### LabelEncoder
class sklearn.preprocessing.LabelEncoder[source]

Encode target labels with value between 0 and n_classes-1.

This transformer should be used to encode target values, i.e. y, and not the input X.

In [ ]:
from sklearn.preprocessing import LabelEncoder

## IMPLEMENTATION On MULTIPLE DATA PRE-PROCESSING METHODS AT A TIME :

- use sklearn column transformer 
- we have to transform X_train and X_test

In [58]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,MinMaxScaler

In [60]:
tf=ColumnTransformer(transformers=[("t1",OrdinalEncoder(),[0,1]),
                                   ("t2",MinMaxScaler(),[2,3,4,5,6])])
X_train_trans=tf.fit_transform(X_train)
X_test_trans=tf.transform(X_test)

In [61]:
X_train.columns

Index(['platform', 'post_type', 'post_length', 'views', 'likes', 'comments',
       'shares'],
      dtype='object')

In [62]:
X_train_trdf=pd.DataFrame(X_train_trans,columns=X_train.columns)
X_train_trdf.head()

   platform  post_type  post_length     views     likes  comments    shares
0       1.0        0.0     0.061404  0.770160  0.332858  0.285237  0.182742
1       1.0        1.0     0.710526  0.460744  0.163186  0.121683  0.107404
2       0.0        2.0     0.473684  0.819741  0.289634  0.226460  0.291189
3       0.0        0.0     0.500000  0.038300  0.039387  0.012778  0.040146
4       0.0        0.0     0.254386  0.638170  0.474143  0.461569  0.230970